/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyStatementRouteImport } from './routes/privacy-statement'
import { Route as MatchMapRouteImport } from './routes/match-map'
import { Route as HuisartsenRouteImport } from './routes/huisartsen'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistrerenIndexRouteImport } from './routes/registreren/index'
import { Route as MatchesIndexRouteImport } from './routes/matches/index'
import { Route as HetProbleemIndexRouteImport } from './routes/het-probleem/index'
import { Route as RegistrerenVoltooidRouteImport } from './routes/registreren/voltooid'
import { Route as RegistrerenStap1RouteImport } from './routes/registreren/stap-1'
import { Route as Registreren_layoutRouteImport } from './routes/registreren/__layout'
import { Route as MatchesMatchIdIndexRouteImport } from './routes/matches/$matchId/index'
import { Route as RegistrerenPostcodeHouseNumberRouteRouteImport } from './routes/registreren/$postcode/$houseNumber/route'
import { Route as RegistrerenPostcodeHouseNumberStap4RouteImport } from './routes/registreren/$postcode/$houseNumber/stap-4'
import { Route as RegistrerenPostcodeHouseNumberStap3RouteImport } from './routes/registreren/$postcode/$houseNumber/stap-3'
import { Route as RegistrerenPostcodeHouseNumberStap2RouteImport } from './routes/registreren/$postcode/$houseNumber/stap-2'

const PrivacyStatementRoute = PrivacyStatementRouteImport.update({
  id: '/privacy-statement',
  path: '/privacy-statement',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMapRoute = MatchMapRouteImport.update({
  id: '/match-map',
  path: '/match-map',
  getParentRoute: () => rootRouteImport,
} as any)
const HuisartsenRoute = HuisartsenRouteImport.update({
  id: '/huisartsen',
  path: '/huisartsen',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrerenIndexRoute = RegistrerenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegistrerenRoute,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const HetProbleemIndexRoute = HetProbleemIndexRouteImport.update({
  id: '/het-probleem/',
  path: '/het-probleem/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrerenVoltooidRoute = RegistrerenVoltooidRouteImport.update({
  id: '/voltooid',
  path: '/voltooid',
  getParentRoute: () => RegistrerenRoute,
} as any)
const RegistrerenStap1Route = RegistrerenStap1RouteImport.update({
  id: '/stap-1',
  path: '/stap-1',
  getParentRoute: () => RegistrerenRoute,
} as any)
const Registreren_layoutRoute = Registreren_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => RegistrerenRoute,
} as any)
const MatchesMatchIdIndexRoute = MatchesMatchIdIndexRouteImport.update({
  id: '/matches/$matchId/',
  path: '/matches/$matchId/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrerenPostcodeHouseNumberRouteRoute =
  RegistrerenPostcodeHouseNumberRouteRouteImport.update({
    id: '/$postcode/$houseNumber',
    path: '/$postcode/$houseNumber',
    getParentRoute: () => RegistrerenRoute,
  } as any)
const RegistrerenPostcodeHouseNumberStap4Route =
  RegistrerenPostcodeHouseNumberStap4RouteImport.update({
    id: '/stap-4',
    path: '/stap-4',
    getParentRoute: () => RegistrerenPostcodeHouseNumberRouteRoute,
  } as any)
const RegistrerenPostcodeHouseNumberStap3Route =
  RegistrerenPostcodeHouseNumberStap3RouteImport.update({
    id: '/stap-3',
    path: '/stap-3',
    getParentRoute: () => RegistrerenPostcodeHouseNumberRouteRoute,
  } as any)
const RegistrerenPostcodeHouseNumberStap2Route =
  RegistrerenPostcodeHouseNumberStap2RouteImport.update({
    id: '/stap-2',
    path: '/stap-2',
    getParentRoute: () => RegistrerenPostcodeHouseNumberRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/huisartsen': typeof HuisartsenRoute
  '/match-map': typeof MatchMapRoute
  '/privacy-statement': typeof PrivacyStatementRoute
  '/registreren': typeof Registreren_layoutRoute
  '/registreren/stap-1': typeof RegistrerenStap1Route
  '/registreren/voltooid': typeof RegistrerenVoltooidRoute
  '/het-probleem': typeof HetProbleemIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/registreren/': typeof RegistrerenIndexRoute
  '/registreren/$postcode/$houseNumber': typeof RegistrerenPostcodeHouseNumberRouteRouteWithChildren
  '/matches/$matchId': typeof MatchesMatchIdIndexRoute
  '/registreren/$postcode/$houseNumber/stap-2': typeof RegistrerenPostcodeHouseNumberStap2Route
  '/registreren/$postcode/$houseNumber/stap-3': typeof RegistrerenPostcodeHouseNumberStap3Route
  '/registreren/$postcode/$houseNumber/stap-4': typeof RegistrerenPostcodeHouseNumberStap4Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/huisartsen': typeof HuisartsenRoute
  '/match-map': typeof MatchMapRoute
  '/privacy-statement': typeof PrivacyStatementRoute
  '/registreren': typeof RegistrerenIndexRoute
  '/registreren/stap-1': typeof RegistrerenStap1Route
  '/registreren/voltooid': typeof RegistrerenVoltooidRoute
  '/het-probleem': typeof HetProbleemIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/registreren/$postcode/$houseNumber': typeof RegistrerenPostcodeHouseNumberRouteRouteWithChildren
  '/matches/$matchId': typeof MatchesMatchIdIndexRoute
  '/registreren/$postcode/$houseNumber/stap-2': typeof RegistrerenPostcodeHouseNumberStap2Route
  '/registreren/$postcode/$houseNumber/stap-3': typeof RegistrerenPostcodeHouseNumberStap3Route
  '/registreren/$postcode/$houseNumber/stap-4': typeof RegistrerenPostcodeHouseNumberStap4Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/huisartsen': typeof HuisartsenRoute
  '/match-map': typeof MatchMapRoute
  '/privacy-statement': typeof PrivacyStatementRoute
  '/registreren/__layout': typeof Registreren_layoutRoute
  '/registreren/stap-1': typeof RegistrerenStap1Route
  '/registreren/voltooid': typeof RegistrerenVoltooidRoute
  '/het-probleem/': typeof HetProbleemIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/registreren/': typeof RegistrerenIndexRoute
  '/registreren/$postcode/$houseNumber': typeof RegistrerenPostcodeHouseNumberRouteRouteWithChildren
  '/matches/$matchId/': typeof MatchesMatchIdIndexRoute
  '/registreren/$postcode/$houseNumber/stap-2': typeof RegistrerenPostcodeHouseNumberStap2Route
  '/registreren/$postcode/$houseNumber/stap-3': typeof RegistrerenPostcodeHouseNumberStap3Route
  '/registreren/$postcode/$houseNumber/stap-4': typeof RegistrerenPostcodeHouseNumberStap4Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/huisartsen'
    | '/match-map'
    | '/privacy-statement'
    | '/registreren'
    | '/registreren/stap-1'
    | '/registreren/voltooid'
    | '/het-probleem'
    | '/matches'
    | '/registreren/'
    | '/registreren/$postcode/$houseNumber'
    | '/matches/$matchId'
    | '/registreren/$postcode/$houseNumber/stap-2'
    | '/registreren/$postcode/$houseNumber/stap-3'
    | '/registreren/$postcode/$houseNumber/stap-4'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/error'
    | '/huisartsen'
    | '/match-map'
    | '/privacy-statement'
    | '/registreren'
    | '/registreren/stap-1'
    | '/registreren/voltooid'
    | '/het-probleem'
    | '/matches'
    | '/registreren/$postcode/$houseNumber'
    | '/matches/$matchId'
    | '/registreren/$postcode/$houseNumber/stap-2'
    | '/registreren/$postcode/$houseNumber/stap-3'
    | '/registreren/$postcode/$houseNumber/stap-4'
  id:
    | '__root__'
    | '/'
    | '/error'
    | '/huisartsen'
    | '/match-map'
    | '/privacy-statement'
    | '/registreren/__layout'
    | '/registreren/stap-1'
    | '/registreren/voltooid'
    | '/het-probleem/'
    | '/matches/'
    | '/registreren/'
    | '/registreren/$postcode/$houseNumber'
    | '/matches/$matchId/'
    | '/registreren/$postcode/$houseNumber/stap-2'
    | '/registreren/$postcode/$houseNumber/stap-3'
    | '/registreren/$postcode/$houseNumber/stap-4'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErrorRoute: typeof ErrorRoute
  HuisartsenRoute: typeof HuisartsenRoute
  MatchMapRoute: typeof MatchMapRoute
  PrivacyStatementRoute: typeof PrivacyStatementRoute
  HetProbleemIndexRoute: typeof HetProbleemIndexRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
  MatchesMatchIdIndexRoute: typeof MatchesMatchIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy-statement': {
      id: '/privacy-statement'
      path: '/privacy-statement'
      fullPath: '/privacy-statement'
      preLoaderRoute: typeof PrivacyStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match-map': {
      id: '/match-map'
      path: '/match-map'
      fullPath: '/match-map'
      preLoaderRoute: typeof MatchMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huisartsen': {
      id: '/huisartsen'
      path: '/huisartsen'
      fullPath: '/huisartsen'
      preLoaderRoute: typeof HuisartsenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registreren/': {
      id: '/registreren/'
      path: '/'
      fullPath: '/registreren/'
      preLoaderRoute: typeof RegistrerenIndexRouteImport
      parentRoute: typeof RegistrerenRoute
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/het-probleem/': {
      id: '/het-probleem/'
      path: '/het-probleem'
      fullPath: '/het-probleem'
      preLoaderRoute: typeof HetProbleemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registreren/voltooid': {
      id: '/registreren/voltooid'
      path: '/voltooid'
      fullPath: '/registreren/voltooid'
      preLoaderRoute: typeof RegistrerenVoltooidRouteImport
      parentRoute: typeof RegistrerenRoute
    }
    '/registreren/stap-1': {
      id: '/registreren/stap-1'
      path: '/stap-1'
      fullPath: '/registreren/stap-1'
      preLoaderRoute: typeof RegistrerenStap1RouteImport
      parentRoute: typeof RegistrerenRoute
    }
    '/registreren/__layout': {
      id: '/registreren/__layout'
      path: ''
      fullPath: '/registreren'
      preLoaderRoute: typeof Registreren_layoutRouteImport
      parentRoute: typeof RegistrerenRoute
    }
    '/matches/$matchId/': {
      id: '/matches/$matchId/'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registreren/$postcode/$houseNumber': {
      id: '/registreren/$postcode/$houseNumber'
      path: '/$postcode/$houseNumber'
      fullPath: '/registreren/$postcode/$houseNumber'
      preLoaderRoute: typeof RegistrerenPostcodeHouseNumberRouteRouteImport
      parentRoute: typeof RegistrerenRoute
    }
    '/registreren/$postcode/$houseNumber/stap-4': {
      id: '/registreren/$postcode/$houseNumber/stap-4'
      path: '/stap-4'
      fullPath: '/registreren/$postcode/$houseNumber/stap-4'
      preLoaderRoute: typeof RegistrerenPostcodeHouseNumberStap4RouteImport
      parentRoute: typeof RegistrerenPostcodeHouseNumberRouteRoute
    }
    '/registreren/$postcode/$houseNumber/stap-3': {
      id: '/registreren/$postcode/$houseNumber/stap-3'
      path: '/stap-3'
      fullPath: '/registreren/$postcode/$houseNumber/stap-3'
      preLoaderRoute: typeof RegistrerenPostcodeHouseNumberStap3RouteImport
      parentRoute: typeof RegistrerenPostcodeHouseNumberRouteRoute
    }
    '/registreren/$postcode/$houseNumber/stap-2': {
      id: '/registreren/$postcode/$houseNumber/stap-2'
      path: '/stap-2'
      fullPath: '/registreren/$postcode/$houseNumber/stap-2'
      preLoaderRoute: typeof RegistrerenPostcodeHouseNumberStap2RouteImport
      parentRoute: typeof RegistrerenPostcodeHouseNumberRouteRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErrorRoute: ErrorRoute,
  HuisartsenRoute: HuisartsenRoute,
  MatchMapRoute: MatchMapRoute,
  PrivacyStatementRoute: PrivacyStatementRoute,
  HetProbleemIndexRoute: HetProbleemIndexRoute,
  MatchesIndexRoute: MatchesIndexRoute,
  MatchesMatchIdIndexRoute: MatchesMatchIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
