/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HuisartsenRouteImport } from './routes/huisartsen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistrerenIndexRouteImport } from './routes/registreren/index'
import { Route as RegistrerenVoltooidRouteImport } from './routes/registreren/voltooid'
import { Route as RegistrerenStap1RouteImport } from './routes/registreren/stap-1'
import { Route as Registreren_layoutRouteImport } from './routes/registreren/__layout'
import { Route as RegistrerenPostcodeRouteRouteImport } from './routes/registreren/$postcode/route'
import { Route as RegistrerenPostcodeStap4RouteImport } from './routes/registreren/$postcode/stap-4'
import { Route as RegistrerenPostcodeStap3RouteImport } from './routes/registreren/$postcode/stap-3'
import { Route as RegistrerenPostcodeStap2RouteImport } from './routes/registreren/$postcode/stap-2'

const HuisartsenRoute = HuisartsenRouteImport.update({
  id: '/huisartsen',
  path: '/huisartsen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrerenIndexRoute = RegistrerenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegistrerenRoute,
} as any)
const RegistrerenVoltooidRoute = RegistrerenVoltooidRouteImport.update({
  id: '/voltooid',
  path: '/voltooid',
  getParentRoute: () => RegistrerenRoute,
} as any)
const RegistrerenStap1Route = RegistrerenStap1RouteImport.update({
  id: '/stap-1',
  path: '/stap-1',
  getParentRoute: () => RegistrerenRoute,
} as any)
const Registreren_layoutRoute = Registreren_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => RegistrerenRoute,
} as any)
const RegistrerenPostcodeRouteRoute =
  RegistrerenPostcodeRouteRouteImport.update({
    id: '/registreren/$postcode',
    path: '/registreren/$postcode',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegistrerenPostcodeStap4Route =
  RegistrerenPostcodeStap4RouteImport.update({
    id: '/stap-4',
    path: '/stap-4',
    getParentRoute: () => RegistrerenPostcodeRouteRoute,
  } as any)
const RegistrerenPostcodeStap3Route =
  RegistrerenPostcodeStap3RouteImport.update({
    id: '/stap-3',
    path: '/stap-3',
    getParentRoute: () => RegistrerenPostcodeRouteRoute,
  } as any)
const RegistrerenPostcodeStap2Route =
  RegistrerenPostcodeStap2RouteImport.update({
    id: '/stap-2',
    path: '/stap-2',
    getParentRoute: () => RegistrerenPostcodeRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/huisartsen': typeof HuisartsenRoute
  '/registreren/$postcode': typeof RegistrerenPostcodeRouteRouteWithChildren
  '/registreren': typeof Registreren_layoutRoute
  '/registreren/stap-1': typeof RegistrerenStap1Route
  '/registreren/voltooid': typeof RegistrerenVoltooidRoute
  '/registreren/': typeof RegistrerenIndexRoute
  '/registreren/$postcode/stap-2': typeof RegistrerenPostcodeStap2Route
  '/registreren/$postcode/stap-3': typeof RegistrerenPostcodeStap3Route
  '/registreren/$postcode/stap-4': typeof RegistrerenPostcodeStap4Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/huisartsen': typeof HuisartsenRoute
  '/registreren/$postcode': typeof RegistrerenPostcodeRouteRouteWithChildren
  '/registreren': typeof RegistrerenIndexRoute
  '/registreren/stap-1': typeof RegistrerenStap1Route
  '/registreren/voltooid': typeof RegistrerenVoltooidRoute
  '/registreren/$postcode/stap-2': typeof RegistrerenPostcodeStap2Route
  '/registreren/$postcode/stap-3': typeof RegistrerenPostcodeStap3Route
  '/registreren/$postcode/stap-4': typeof RegistrerenPostcodeStap4Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/huisartsen': typeof HuisartsenRoute
  '/registreren/$postcode': typeof RegistrerenPostcodeRouteRouteWithChildren
  '/registreren/__layout': typeof Registreren_layoutRoute
  '/registreren/stap-1': typeof RegistrerenStap1Route
  '/registreren/voltooid': typeof RegistrerenVoltooidRoute
  '/registreren/': typeof RegistrerenIndexRoute
  '/registreren/$postcode/stap-2': typeof RegistrerenPostcodeStap2Route
  '/registreren/$postcode/stap-3': typeof RegistrerenPostcodeStap3Route
  '/registreren/$postcode/stap-4': typeof RegistrerenPostcodeStap4Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/huisartsen'
    | '/registreren/$postcode'
    | '/registreren'
    | '/registreren/stap-1'
    | '/registreren/voltooid'
    | '/registreren/'
    | '/registreren/$postcode/stap-2'
    | '/registreren/$postcode/stap-3'
    | '/registreren/$postcode/stap-4'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/huisartsen'
    | '/registreren/$postcode'
    | '/registreren'
    | '/registreren/stap-1'
    | '/registreren/voltooid'
    | '/registreren/$postcode/stap-2'
    | '/registreren/$postcode/stap-3'
    | '/registreren/$postcode/stap-4'
  id:
    | '__root__'
    | '/'
    | '/huisartsen'
    | '/registreren/$postcode'
    | '/registreren/__layout'
    | '/registreren/stap-1'
    | '/registreren/voltooid'
    | '/registreren/'
    | '/registreren/$postcode/stap-2'
    | '/registreren/$postcode/stap-3'
    | '/registreren/$postcode/stap-4'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HuisartsenRoute: typeof HuisartsenRoute
  RegistrerenPostcodeRouteRoute: typeof RegistrerenPostcodeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/huisartsen': {
      id: '/huisartsen'
      path: '/huisartsen'
      fullPath: '/huisartsen'
      preLoaderRoute: typeof HuisartsenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registreren/': {
      id: '/registreren/'
      path: '/'
      fullPath: '/registreren/'
      preLoaderRoute: typeof RegistrerenIndexRouteImport
      parentRoute: typeof RegistrerenRoute
    }
    '/registreren/voltooid': {
      id: '/registreren/voltooid'
      path: '/voltooid'
      fullPath: '/registreren/voltooid'
      preLoaderRoute: typeof RegistrerenVoltooidRouteImport
      parentRoute: typeof RegistrerenRoute
    }
    '/registreren/stap-1': {
      id: '/registreren/stap-1'
      path: '/stap-1'
      fullPath: '/registreren/stap-1'
      preLoaderRoute: typeof RegistrerenStap1RouteImport
      parentRoute: typeof RegistrerenRoute
    }
    '/registreren/__layout': {
      id: '/registreren/__layout'
      path: ''
      fullPath: '/registreren'
      preLoaderRoute: typeof Registreren_layoutRouteImport
      parentRoute: typeof RegistrerenRoute
    }
    '/registreren/$postcode': {
      id: '/registreren/$postcode'
      path: '/registreren/$postcode'
      fullPath: '/registreren/$postcode'
      preLoaderRoute: typeof RegistrerenPostcodeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registreren/$postcode/stap-4': {
      id: '/registreren/$postcode/stap-4'
      path: '/stap-4'
      fullPath: '/registreren/$postcode/stap-4'
      preLoaderRoute: typeof RegistrerenPostcodeStap4RouteImport
      parentRoute: typeof RegistrerenPostcodeRouteRoute
    }
    '/registreren/$postcode/stap-3': {
      id: '/registreren/$postcode/stap-3'
      path: '/stap-3'
      fullPath: '/registreren/$postcode/stap-3'
      preLoaderRoute: typeof RegistrerenPostcodeStap3RouteImport
      parentRoute: typeof RegistrerenPostcodeRouteRoute
    }
    '/registreren/$postcode/stap-2': {
      id: '/registreren/$postcode/stap-2'
      path: '/stap-2'
      fullPath: '/registreren/$postcode/stap-2'
      preLoaderRoute: typeof RegistrerenPostcodeStap2RouteImport
      parentRoute: typeof RegistrerenPostcodeRouteRoute
    }
  }
}

interface RegistrerenPostcodeRouteRouteChildren {
  RegistrerenPostcodeStap2Route: typeof RegistrerenPostcodeStap2Route
  RegistrerenPostcodeStap3Route: typeof RegistrerenPostcodeStap3Route
  RegistrerenPostcodeStap4Route: typeof RegistrerenPostcodeStap4Route
}

const RegistrerenPostcodeRouteRouteChildren: RegistrerenPostcodeRouteRouteChildren =
  {
    RegistrerenPostcodeStap2Route: RegistrerenPostcodeStap2Route,
    RegistrerenPostcodeStap3Route: RegistrerenPostcodeStap3Route,
    RegistrerenPostcodeStap4Route: RegistrerenPostcodeStap4Route,
  }

const RegistrerenPostcodeRouteRouteWithChildren =
  RegistrerenPostcodeRouteRoute._addFileChildren(
    RegistrerenPostcodeRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HuisartsenRoute: HuisartsenRoute,
  RegistrerenPostcodeRouteRoute: RegistrerenPostcodeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
