/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as HuisartsenRouteImport } from './routes/huisartsen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistrerenIndexRouteImport } from './routes/registreren/index'
import { Route as RegistrerenVoltooidRouteImport } from './routes/registreren/voltooid'
import { Route as RegistrerenStap1RouteImport } from './routes/registreren/stap-1'
import { Route as Registreren_layoutRouteImport } from './routes/registreren/__layout'
import { Route as RegistrerenPostcodeStap4RouteImport } from './routes/registreren/$postcode/stap-4'
import { Route as RegistrerenPostcodeStap3RouteImport } from './routes/registreren/$postcode/stap-3'
import { Route as RegistrerenPostcodeStap2RouteImport } from './routes/registreren/$postcode/stap-2'
import { Route as RegistrerenPostcode_layoutRouteImport } from './routes/registreren/$postcode/__layout'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const RegistrerenRouteImport = createFileRoute('/registreren')()
const RegistrerenPostcodeRouteImport = createFileRoute(
  '/registreren/$postcode',
)()

const RegistrerenRoute = RegistrerenRouteImport.update({
  id: '/registreren',
  path: '/registreren',
  getParentRoute: () => rootRouteImport,
} as any)
const HuisartsenRoute = HuisartsenRouteImport.update({
  id: '/huisartsen',
  path: '/huisartsen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrerenPostcodeRoute = RegistrerenPostcodeRouteImport.update({
  id: '/$postcode',
  path: '/$postcode',
  getParentRoute: () => RegistrerenRoute,
} as any)
const RegistrerenIndexRoute = RegistrerenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegistrerenRoute,
} as any)
const RegistrerenVoltooidRoute = RegistrerenVoltooidRouteImport.update({
  id: '/voltooid',
  path: '/voltooid',
  getParentRoute: () => RegistrerenRoute,
} as any)
const RegistrerenStap1Route = RegistrerenStap1RouteImport.update({
  id: '/stap-1',
  path: '/stap-1',
  getParentRoute: () => RegistrerenRoute,
} as any)
const Registreren_layoutRoute = Registreren_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => RegistrerenRoute,
} as any)
const RegistrerenPostcodeStap4Route =
  RegistrerenPostcodeStap4RouteImport.update({
    id: '/stap-4',
    path: '/stap-4',
    getParentRoute: () => RegistrerenPostcodeRoute,
  } as any)
const RegistrerenPostcodeStap3Route =
  RegistrerenPostcodeStap3RouteImport.update({
    id: '/stap-3',
    path: '/stap-3',
    getParentRoute: () => RegistrerenPostcodeRoute,
  } as any)
const RegistrerenPostcodeStap2Route =
  RegistrerenPostcodeStap2RouteImport.update({
    id: '/stap-2',
    path: '/stap-2',
    getParentRoute: () => RegistrerenPostcodeRoute,
  } as any)
const RegistrerenPostcode_layoutRoute =
  RegistrerenPostcode_layoutRouteImport.update({
    id: '/__layout',
    getParentRoute: () => RegistrerenPostcodeRoute,
  } as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/huisartsen': typeof HuisartsenRoute
  '/registreren': typeof Registreren_layoutRoute
  '/registreren/stap-1': typeof RegistrerenStap1Route
  '/registreren/voltooid': typeof RegistrerenVoltooidRoute
  '/registreren/': typeof RegistrerenIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/registreren/$postcode': typeof RegistrerenPostcode_layoutRoute
  '/registreren/$postcode/stap-2': typeof RegistrerenPostcodeStap2Route
  '/registreren/$postcode/stap-3': typeof RegistrerenPostcodeStap3Route
  '/registreren/$postcode/stap-4': typeof RegistrerenPostcodeStap4Route
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/huisartsen': typeof HuisartsenRoute
  '/registreren': typeof RegistrerenIndexRoute
  '/registreren/stap-1': typeof RegistrerenStap1Route
  '/registreren/voltooid': typeof RegistrerenVoltooidRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/registreren/$postcode': typeof RegistrerenPostcode_layoutRoute
  '/registreren/$postcode/stap-2': typeof RegistrerenPostcodeStap2Route
  '/registreren/$postcode/stap-3': typeof RegistrerenPostcodeStap3Route
  '/registreren/$postcode/stap-4': typeof RegistrerenPostcodeStap4Route
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/huisartsen': typeof HuisartsenRoute
  '/registreren': typeof RegistrerenRouteWithChildren
  '/registreren/__layout': typeof Registreren_layoutRoute
  '/registreren/stap-1': typeof RegistrerenStap1Route
  '/registreren/voltooid': typeof RegistrerenVoltooidRoute
  '/registreren/': typeof RegistrerenIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/registreren/$postcode': typeof RegistrerenPostcodeRouteWithChildren
  '/registreren/$postcode/__layout': typeof RegistrerenPostcode_layoutRoute
  '/registreren/$postcode/stap-2': typeof RegistrerenPostcodeStap2Route
  '/registreren/$postcode/stap-3': typeof RegistrerenPostcodeStap3Route
  '/registreren/$postcode/stap-4': typeof RegistrerenPostcodeStap4Route
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/huisartsen'
    | '/registreren'
    | '/registreren/stap-1'
    | '/registreren/voltooid'
    | '/registreren/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/registreren/$postcode'
    | '/registreren/$postcode/stap-2'
    | '/registreren/$postcode/stap-3'
    | '/registreren/$postcode/stap-4'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/huisartsen'
    | '/registreren'
    | '/registreren/stap-1'
    | '/registreren/voltooid'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/registreren/$postcode'
    | '/registreren/$postcode/stap-2'
    | '/registreren/$postcode/stap-3'
    | '/registreren/$postcode/stap-4'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/huisartsen'
    | '/registreren'
    | '/registreren/__layout'
    | '/registreren/stap-1'
    | '/registreren/voltooid'
    | '/registreren/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/registreren/$postcode'
    | '/registreren/$postcode/__layout'
    | '/registreren/$postcode/stap-2'
    | '/registreren/$postcode/stap-3'
    | '/registreren/$postcode/stap-4'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HuisartsenRoute: typeof HuisartsenRoute
  RegistrerenRoute: typeof RegistrerenRouteWithChildren
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registreren': {
      id: '/registreren'
      path: '/registreren'
      fullPath: '/registreren'
      preLoaderRoute: typeof RegistrerenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huisartsen': {
      id: '/huisartsen'
      path: '/huisartsen'
      fullPath: '/huisartsen'
      preLoaderRoute: typeof HuisartsenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registreren/$postcode': {
      id: '/registreren/$postcode'
      path: '/$postcode'
      fullPath: '/registreren/$postcode'
      preLoaderRoute: typeof RegistrerenPostcodeRouteImport
      parentRoute: typeof RegistrerenRoute
    }
    '/registreren/': {
      id: '/registreren/'
      path: '/'
      fullPath: '/registreren/'
      preLoaderRoute: typeof RegistrerenIndexRouteImport
      parentRoute: typeof RegistrerenRoute
    }
    '/registreren/voltooid': {
      id: '/registreren/voltooid'
      path: '/voltooid'
      fullPath: '/registreren/voltooid'
      preLoaderRoute: typeof RegistrerenVoltooidRouteImport
      parentRoute: typeof RegistrerenRoute
    }
    '/registreren/stap-1': {
      id: '/registreren/stap-1'
      path: '/stap-1'
      fullPath: '/registreren/stap-1'
      preLoaderRoute: typeof RegistrerenStap1RouteImport
      parentRoute: typeof RegistrerenRoute
    }
    '/registreren/__layout': {
      id: '/registreren/__layout'
      path: '/registreren'
      fullPath: '/registreren'
      preLoaderRoute: typeof Registreren_layoutRouteImport
      parentRoute: typeof RegistrerenRoute
    }
    '/registreren/$postcode/stap-4': {
      id: '/registreren/$postcode/stap-4'
      path: '/stap-4'
      fullPath: '/registreren/$postcode/stap-4'
      preLoaderRoute: typeof RegistrerenPostcodeStap4RouteImport
      parentRoute: typeof RegistrerenPostcodeRoute
    }
    '/registreren/$postcode/stap-3': {
      id: '/registreren/$postcode/stap-3'
      path: '/stap-3'
      fullPath: '/registreren/$postcode/stap-3'
      preLoaderRoute: typeof RegistrerenPostcodeStap3RouteImport
      parentRoute: typeof RegistrerenPostcodeRoute
    }
    '/registreren/$postcode/stap-2': {
      id: '/registreren/$postcode/stap-2'
      path: '/stap-2'
      fullPath: '/registreren/$postcode/stap-2'
      preLoaderRoute: typeof RegistrerenPostcodeStap2RouteImport
      parentRoute: typeof RegistrerenPostcodeRoute
    }
    '/registreren/$postcode/__layout': {
      id: '/registreren/$postcode/__layout'
      path: '/$postcode'
      fullPath: '/registreren/$postcode'
      preLoaderRoute: typeof RegistrerenPostcode_layoutRouteImport
      parentRoute: typeof RegistrerenPostcodeRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RegistrerenPostcodeRouteChildren {
  RegistrerenPostcode_layoutRoute: typeof RegistrerenPostcode_layoutRoute
  RegistrerenPostcodeStap2Route: typeof RegistrerenPostcodeStap2Route
  RegistrerenPostcodeStap3Route: typeof RegistrerenPostcodeStap3Route
  RegistrerenPostcodeStap4Route: typeof RegistrerenPostcodeStap4Route
}

const RegistrerenPostcodeRouteChildren: RegistrerenPostcodeRouteChildren = {
  RegistrerenPostcode_layoutRoute: RegistrerenPostcode_layoutRoute,
  RegistrerenPostcodeStap2Route: RegistrerenPostcodeStap2Route,
  RegistrerenPostcodeStap3Route: RegistrerenPostcodeStap3Route,
  RegistrerenPostcodeStap4Route: RegistrerenPostcodeStap4Route,
}

const RegistrerenPostcodeRouteWithChildren =
  RegistrerenPostcodeRoute._addFileChildren(RegistrerenPostcodeRouteChildren)

interface RegistrerenRouteChildren {
  Registreren_layoutRoute: typeof Registreren_layoutRoute
  RegistrerenStap1Route: typeof RegistrerenStap1Route
  RegistrerenVoltooidRoute: typeof RegistrerenVoltooidRoute
  RegistrerenIndexRoute: typeof RegistrerenIndexRoute
  RegistrerenPostcodeRoute: typeof RegistrerenPostcodeRouteWithChildren
}

const RegistrerenRouteChildren: RegistrerenRouteChildren = {
  Registreren_layoutRoute: Registreren_layoutRoute,
  RegistrerenStap1Route: RegistrerenStap1Route,
  RegistrerenVoltooidRoute: RegistrerenVoltooidRoute,
  RegistrerenIndexRoute: RegistrerenIndexRoute,
  RegistrerenPostcodeRoute: RegistrerenPostcodeRouteWithChildren,
}

const RegistrerenRouteWithChildren = RegistrerenRoute._addFileChildren(
  RegistrerenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HuisartsenRoute: HuisartsenRoute,
  RegistrerenRoute: RegistrerenRouteWithChildren,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
